from collections import namedtuple
from dataclasses import dataclass
from typing import Optional, Callable
from enum import Enum
from BaseClasses import Region, Location, Entrance, Item, ItemClassification
from .Rules import RuleFlag, get_rule_for_location
from .Names import LairID, LairName, ChestID, ChestName, NPCRewardID, NPCRewardName
from .Names.ArchipelagoID import BASE_ID, LAIR_ID_OFFSET, NPC_REWARD_OFFSET


# TODO: Use IntEnum instead?
class LocationType(Enum):
    CHEST = "Chest"
    """Location checked by opening a chest."""
    NPC_REWARD = "NPC Reward"
    """Location checked by talking to an NPC or stepping on an item tile."""
    LAIR = "Lair"
    """Location checked by sealing a monster lair."""


def address_for_location(type: LocationType, id: int) -> int:
    if type == LocationType.LAIR:
        return BASE_ID + LAIR_ID_OFFSET + id
    if type == LocationType.NPC_REWARD:
        return BASE_ID + NPC_REWARD_OFFSET + id
    return BASE_ID + id


@dataclass(frozen=True)
class LocationData():
    id: int
    """Internal location ID and index into ROM chest/lair/NPC reward table"""
    type: LocationType
    flag: RuleFlag = RuleFlag.NONE

    @property
    def address(self) -> int:
        """The unique ID used by archipelago for this location"""

        if self.type == LocationType.LAIR:
            return BASE_ID + LAIR_ID_OFFSET + self.id
        if self.type == LocationType.NPC_REWARD:
            return BASE_ID + NPC_REWARD_OFFSET + self.id
        return BASE_ID + self.id


class SoulBlazerLocation(Location):
    game = "Soul Blazer"

    def __init__(
        self, player: int, name: str, data: LocationData, parent: Optional[Region] = None
    ):
        super().__init__(player, name, data.address, parent)
        self.data: LocationData = data
        self.access_rule = get_rule_for_location(name, player, self.data.flag)


# TODO: move data into yaml or json?
chest_table = {
    ChestName.TRIAL_ROOM                     : LocationData(ChestID.TRIAL_ROOM                    , LocationType.CHEST),
    ChestName.GRASS_VALLEY_SECRET_CAVE_LEFT  : LocationData(ChestID.GRASS_VALLEY_SECRET_CAVE_LEFT , LocationType.CHEST),
    ChestName.GRASS_VALLEY_SECRET_CAVE_RIGHT : LocationData(ChestID.GRASS_VALLEY_SECRET_CAVE_RIGHT, LocationType.CHEST),
    ChestName.UNDERGROUND_CASTLE_12GEM       : LocationData(ChestID.UNDERGROUND_CASTLE_12GEM      , LocationType.CHEST),
    ChestName.UNDERGROUND_CASTLE_HERB        : LocationData(ChestID.UNDERGROUND_CASTLE_HERB       , LocationType.CHEST),
    ChestName.UNDERGROUND_CASTLE_DREAM_ROD   : LocationData(ChestID.UNDERGROUND_CASTLE_DREAM_ROD  , LocationType.CHEST),
    ChestName.UNDERGROUND_CASTLE_LEOS_BRUSH  : LocationData(ChestID.UNDERGROUND_CASTLE_LEOS_BRUSH , LocationType.CHEST),
    ChestName.LEOS_PAINTING_HERB             : LocationData(ChestID.LEOS_PAINTING_HERB            , LocationType.CHEST),
    ChestName.LEOS_PAINTING_TORNADO          : LocationData(ChestID.LEOS_PAINTING_TORNADO         , LocationType.CHEST, RuleFlag.CAN_CUT_METAL),
    ChestName.GREENWOOD_ICE_ARMOR            : LocationData(ChestID.GREENWOOD_ICE_ARMOR           , LocationType.CHEST),
    ChestName.GREENWOOD_TUNNELS              : LocationData(ChestID.GREENWOOD_TUNNELS             , LocationType.CHEST),
    ChestName.WATER_SHRINE_1                 : LocationData(ChestID.WATER_SHRINE_1                , LocationType.CHEST),
    ChestName.WATER_SHRINE_2_N               : LocationData(ChestID.WATER_SHRINE_2_N              , LocationType.CHEST),
    ChestName.WATER_SHRINE_2_HERB            : LocationData(ChestID.WATER_SHRINE_2_HERB           , LocationType.CHEST),
    ChestName.WATER_SHRINE_3_SW              : LocationData(ChestID.WATER_SHRINE_3_SW             , LocationType.CHEST),
    ChestName.WATER_SHRINE_3_SE              : LocationData(ChestID.WATER_SHRINE_3_SE             , LocationType.CHEST),
    ChestName.FIRE_SHRINE_1                  : LocationData(ChestID.FIRE_SHRINE_1                 , LocationType.CHEST),
    ChestName.FIRE_SHRINE_2_DISAPPEARING     : LocationData(ChestID.FIRE_SHRINE_2_DISAPPEARING    , LocationType.CHEST),
    ChestName.FIRE_SHRINE_2_SCORPION         : LocationData(ChestID.FIRE_SHRINE_2_SCORPION        , LocationType.CHEST, RuleFlag.CAN_CUT_METAL),
    ChestName.FIRE_SHRINE_3_100GEM           : LocationData(ChestID.FIRE_SHRINE_3_100GEM          , LocationType.CHEST),
    ChestName.FIRE_SHRINE_3_60GEM            : LocationData(ChestID.FIRE_SHRINE_3_60GEM           , LocationType.CHEST),
    ChestName.LIGHT_SHRINE                   : LocationData(ChestID.LIGHT_SHRINE                  , LocationType.CHEST, RuleFlag.CAN_CUT_SPIRIT),
    ChestName.ST_ELLIS_MERMAIDS_TEARS        : LocationData(ChestID.ST_ELLIS_MERMAIDS_TEARS       , LocationType.CHEST),
    ChestName.ST_ELLIS_BIG_PEARL             : LocationData(ChestID.ST_ELLIS_BIG_PEARL            , LocationType.CHEST),
    ChestName.SEABED_SECRET_TL               : LocationData(ChestID.SEABED_SECRET_TL              , LocationType.CHEST),
    ChestName.SEABED_SECRET_TR               : LocationData(ChestID.SEABED_SECRET_TR              , LocationType.CHEST),
    ChestName.SEABED_SECRET_BL               : LocationData(ChestID.SEABED_SECRET_BL              , LocationType.CHEST),
    ChestName.SEABED_SECRET_BR               : LocationData(ChestID.SEABED_SECRET_BR              , LocationType.CHEST),
    ChestName.SOUTHERTA                      : LocationData(ChestID.SOUTHERTA                     , LocationType.CHEST),
    ChestName.ROCKBIRD_HERB                  : LocationData(ChestID.ROCKBIRD_HERB                 , LocationType.CHEST),
    ChestName.ROCKBIRD_60GEM                 : LocationData(ChestID.ROCKBIRD_60GEM                , LocationType.CHEST),
    ChestName.DUREAN_CRITICAL_SWORD          : LocationData(ChestID.DUREAN_CRITICAL_SWORD         , LocationType.CHEST),
    ChestName.DUREAN_STRANGE_BOTTLE          : LocationData(ChestID.DUREAN_STRANGE_BOTTLE         , LocationType.CHEST),
    ChestName.GHOST_SHIP                     : LocationData(ChestID.GHOST_SHIP                    , LocationType.CHEST),
    ChestName.SEABED_POWER_BRACELET          : LocationData(ChestID.SEABED_POWER_BRACELET         , LocationType.CHEST),
    ChestName.MOUNTAIN_OF_SOULS_1            : LocationData(ChestID.MOUNTAIN_OF_SOULS_1           , LocationType.CHEST),
    ChestName.MOUNTAIN_OF_SOULS_2_LL         : LocationData(ChestID.MOUNTAIN_OF_SOULS_2_LL        , LocationType.CHEST),
    ChestName.MOUNTAIN_OF_SOULS_2_L          : LocationData(ChestID.MOUNTAIN_OF_SOULS_2_L         , LocationType.CHEST),
    ChestName.MOUNTAIN_OF_SOULS_2_R          : LocationData(ChestID.MOUNTAIN_OF_SOULS_2_R         , LocationType.CHEST),
    ChestName.MOUNTAIN_OF_SOULS_2_RR         : LocationData(ChestID.MOUNTAIN_OF_SOULS_2_RR        , LocationType.CHEST),
    ChestName.LAYNOLE_LUCKY_BLADE            : LocationData(ChestID.LAYNOLE_LUCKY_BLADE           , LocationType.CHEST),
    ChestName.LAYNOLE_HERB                   : LocationData(ChestID.LAYNOLE_HERB                  , LocationType.CHEST),
    ChestName.LAYNOLE_ROTATOR                : LocationData(ChestID.LAYNOLE_ROTATOR               , LocationType.CHEST),
    ChestName.LEOS_LAB_ZANTETSU              : LocationData(ChestID.LEOS_LAB_ZANTETSU             , LocationType.CHEST),
    ChestName.POWER_PLANT_LIGHT_ARMOR        : LocationData(ChestID.POWER_PLANT_LIGHT_ARMOR       , LocationType.CHEST, RuleFlag.CAN_CUT_METAL),
    ChestName.MODEL_TOWN_1_SE                : LocationData(ChestID.MODEL_TOWN_1_SE               , LocationType.CHEST),
    ChestName.MODEL_TOWN_1_NL                : LocationData(ChestID.MODEL_TOWN_1_NL               , LocationType.CHEST),
    ChestName.MODEL_TOWN_1_NR                : LocationData(ChestID.MODEL_TOWN_1_NR               , LocationType.CHEST),
    ChestName.MODEL_TOWN_2_TOP               : LocationData(ChestID.MODEL_TOWN_2_TOP              , LocationType.CHEST),
    ChestName.MODEL_TOWN_2_BOT               : LocationData(ChestID.MODEL_TOWN_2_BOT              , LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_1_W            : LocationData(ChestID.CASTLE_BASEMENT_1_W           , LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_1_SPIRIT_SWORD : LocationData(ChestID.CASTLE_BASEMENT_1_SPIRIT_SWORD, LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_2_N            : LocationData(ChestID.CASTLE_BASEMENT_2_N           , LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_2_SW           : LocationData(ChestID.CASTLE_BASEMENT_2_SW          , LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_2_MIDDLE       : LocationData(ChestID.CASTLE_BASEMENT_2_MIDDLE      , LocationType.CHEST),
    ChestName.CASTLE_BASEMENT_3              : LocationData(ChestID.CASTLE_BASEMENT_3             , LocationType.CHEST),
    ChestName.CASTLE_RIGHT_TOWER_2_L         : LocationData(ChestID.CASTLE_RIGHT_TOWER_2_L        , LocationType.CHEST),
    ChestName.CASTLE_RIGHT_TOWER_2_R         : LocationData(ChestID.CASTLE_RIGHT_TOWER_2_R        , LocationType.CHEST),
    ChestName.CASTLE_RIGHT_TOWER_3_TL        : LocationData(ChestID.CASTLE_RIGHT_TOWER_3_TL       , LocationType.CHEST),
    ChestName.CASTLE_RIGHT_TOWER_3_BR        : LocationData(ChestID.CASTLE_RIGHT_TOWER_3_BR       , LocationType.CHEST),
    ChestName.WOE_1_SE                       : LocationData(ChestID.WOE_1_SE                      , LocationType.CHEST, RuleFlag.HAS_MAGIC),
    ChestName.WOE_1_SW                       : LocationData(ChestID.WOE_1_SW                      , LocationType.CHEST, RuleFlag.HAS_MAGIC),
    ChestName.WOE_1_REDHOT_BALL              : LocationData(ChestID.WOE_1_REDHOT_BALL             , LocationType.CHEST, RuleFlag.HAS_MAGIC),
    ChestName.WOE_2                          : LocationData(ChestID.WOE_2                         , LocationType.CHEST),
    ChestName.DAZZLING_SPACE_SE              : LocationData(ChestID.DAZZLING_SPACE_SE             , LocationType.CHEST),
    ChestName.DAZZLING_SPACE_SW              : LocationData(ChestID.DAZZLING_SPACE_SW             , LocationType.CHEST),
}

npc_reward_table = {
    NPCRewardName.TOOL_SHOP_OWNER                  : LocationData(NPCRewardID.TOOL_SHOP_OWNER                 , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_A_TILE                    : LocationData(NPCRewardID.EMBLEM_A_TILE                   , LocationType.NPC_REWARD),
    NPCRewardName.GOAT_PEN_CORNER                  : LocationData(NPCRewardID.GOAT_PEN_CORNER                 , LocationType.NPC_REWARD),
    NPCRewardName.TEDDY                            : LocationData(NPCRewardID.TEDDY                           , LocationType.NPC_REWARD),
    NPCRewardName.PASS_TILE                        : LocationData(NPCRewardID.PASS_TILE                       , LocationType.NPC_REWARD),
    NPCRewardName.TILE_IN_CHILDS_SECRET_CAVE       : LocationData(NPCRewardID.TILE_IN_CHILDS_SECRET_CAVE      , LocationType.NPC_REWARD),
    NPCRewardName.VILLAGE_CHIEF                    : LocationData(NPCRewardID.VILLAGE_CHIEF                   , LocationType.NPC_REWARD),
    NPCRewardName.MAGICIAN                         : LocationData(NPCRewardID.MAGICIAN                        , LocationType.NPC_REWARD, RuleFlag.HAS_SWORD),
    NPCRewardName.RECOVERY_SWORD_CRYSTAL           : LocationData(NPCRewardID.RECOVERY_SWORD_CRYSTAL          , LocationType.NPC_REWARD),
    NPCRewardName.GRASS_VALLEY_SECRET_ROOM_CRYSTAL : LocationData(NPCRewardID.GRASS_VALLEY_SECRET_ROOM_CRYSTAL, LocationType.NPC_REWARD),
    NPCRewardName.UNDERGROUND_CASTLE_CRYSTAL       : LocationData(NPCRewardID.UNDERGROUND_CASTLE_CRYSTAL      , LocationType.NPC_REWARD),
    NPCRewardName.REDHOT_MIRROR_BIRD               : LocationData(NPCRewardID.REDHOT_MIRROR_BIRD              , LocationType.NPC_REWARD),
    NPCRewardName.MAGIC_BELL_CRYSTAL               : LocationData(NPCRewardID.MAGIC_BELL_CRYSTAL              , LocationType.NPC_REWARD),
    NPCRewardName.WOODSTIN_TRIO                    : LocationData(NPCRewardID.WOODSTIN_TRIO                   , LocationType.NPC_REWARD),
    NPCRewardName.GREENWOODS_GUARDIAN              : LocationData(NPCRewardID.GREENWOODS_GUARDIAN             , LocationType.NPC_REWARD),
    NPCRewardName.GREENWOOD_LEAVES_TILE            : LocationData(NPCRewardID.GREENWOOD_LEAVES_TILE           , LocationType.NPC_REWARD),
    NPCRewardName.SHIELD_BRACELET_MOLE             : LocationData(NPCRewardID.SHIELD_BRACELET_MOLE            , LocationType.NPC_REWARD),
    NPCRewardName.PSYCHO_SWORD_SQUIRREL            : LocationData(NPCRewardID.PSYCHO_SWORD_SQUIRREL           , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_C_SQUIRREL                : LocationData(NPCRewardID.EMBLEM_C_SQUIRREL               , LocationType.NPC_REWARD),
    NPCRewardName.WATER_SHRINE_TILE                : LocationData(NPCRewardID.WATER_SHRINE_STRANGE_BOTTLE     , LocationType.NPC_REWARD),
    NPCRewardName.LIGHT_ARROW_CRYSTAL              : LocationData(NPCRewardID.LIGHT_ARROW_CRYSTAL             , LocationType.NPC_REWARD),
    NPCRewardName.LOST_MARSH_CRYSTAL               : LocationData(NPCRewardID.LOST_MARSH_CRYSTAL              , LocationType.NPC_REWARD),
    NPCRewardName.WATER_SHRINE_CRYSTAL             : LocationData(NPCRewardID.WATER_SHRINE_CRYSTAL            , LocationType.NPC_REWARD),
    NPCRewardName.FIRE_SHRINE_CRYSTAL              : LocationData(NPCRewardID.FIRE_SHRINE_CRYSTAL             , LocationType.NPC_REWARD, RuleFlag.CAN_CUT_METAL),
    NPCRewardName.MOUNTAIN_KING                    : LocationData(NPCRewardID.MOUNTAIN_KING                   , LocationType.NPC_REWARD),
    NPCRewardName.MUSHROOM_SHOES_BOY               : LocationData(NPCRewardID.MUSHROOM_SHOES_BOY              , LocationType.NPC_REWARD),
    NPCRewardName.NOME                             : LocationData(NPCRewardID.NOME                            , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_E_SNAIL                   : LocationData(NPCRewardID.EMBLEM_E_SNAIL                  , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_F_TILE                    : LocationData(NPCRewardID.EMBLEM_F_TILE                   , LocationType.NPC_REWARD),
    NPCRewardName.MOUNTAIN_OF_SOULS_CRYSTAL        : LocationData(NPCRewardID.MOUNTAIN_OF_SOULS_CRYSTAL       , LocationType.NPC_REWARD),
    NPCRewardName.LUNE_CRYSTAL                     : LocationData(NPCRewardID.LUNE_CRYSTAL                    , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_G_UNDER_CHEST_OF_DRAWERS  : LocationData(NPCRewardID.EMBLEM_G_UNDER_CHEST_OF_DRAWERS , LocationType.NPC_REWARD),
    NPCRewardName.CHEST_OF_DRAWERS_MYSTIC_ARMOR    : LocationData(NPCRewardID.CHEST_OF_DRAWERS_MYSTIC_ARMOR   , LocationType.NPC_REWARD),
    NPCRewardName.HERB_PLANT_IN_LEOS_LAB           : LocationData(NPCRewardID.HERB_PLANT_IN_LEOS_LAB          , LocationType.NPC_REWARD),
    NPCRewardName.LEOS_CAT_DOOR_KEY                : LocationData(NPCRewardID.LEOS_CAT_DOOR_KEY               , LocationType.NPC_REWARD),
    NPCRewardName.ACTINIDIA_PLANT                  : LocationData(NPCRewardID.ACTINIDIA_PLANT                 , LocationType.NPC_REWARD),
    NPCRewardName.CHEST_OF_DRAWERS_HERB            : LocationData(NPCRewardID.CHEST_OF_DRAWERS_HERB           , LocationType.NPC_REWARD),
    NPCRewardName.MARIE                            : LocationData(NPCRewardID.MARIE                           , LocationType.NPC_REWARD),
    NPCRewardName.SPARK_BOMB_MOUSE                 : LocationData(NPCRewardID.SPARK_BOMB_MOUSE                , LocationType.NPC_REWARD),
    NPCRewardName.LEOS_LAB_BASEMENT_CRYSTAL        : LocationData(NPCRewardID.LEOS_LAB_BASEMENT_CRYSTAL       , LocationType.NPC_REWARD),
    NPCRewardName.MODEL_TOWN_1_CRYSTAL             : LocationData(NPCRewardID.MODEL_TOWN_1_CRYSTAL            , LocationType.NPC_REWARD),
    NPCRewardName.POWER_PLANT_CRYSTAL              : LocationData(NPCRewardID.POWER_PLANT_CRYSTAL             , LocationType.NPC_REWARD, RuleFlag.CAN_CUT_METAL),
    NPCRewardName.ELEMENTAL_MAIL_SOLDIER           : LocationData(NPCRewardID.ELEMENTAL_MAIL_SOLDIER          , LocationType.NPC_REWARD),
    NPCRewardName.SUPER_BRACELET_TILE              : LocationData(NPCRewardID.SUPER_BRACELET_TILE             , LocationType.NPC_REWARD),
    NPCRewardName.QUEEN_MAGRIDD_VIP_CARD           : LocationData(NPCRewardID.QUEEN_MAGRIDD_VIP_CARD          , LocationType.NPC_REWARD),
    NPCRewardName.PLATINUM_CARD_SOLDIER            : LocationData(NPCRewardID.PLATINUM_CARD_SOLDIER           , LocationType.NPC_REWARD),
    NPCRewardName.MAID_HERB                        : LocationData(NPCRewardID.MAID_HERB                       , LocationType.NPC_REWARD),
    NPCRewardName.EMBLEM_H_TILE                    : LocationData(NPCRewardID.EMBLEM_H_TILE                   , LocationType.NPC_REWARD),
    NPCRewardName.KING_MAGRIDD                     : LocationData(NPCRewardID.KING_MAGRIDD                    , LocationType.NPC_REWARD),
    NPCRewardName.LEO_ON_THE_AIRSHIP_DECK          : LocationData(NPCRewardID.LEO_ON_THE_AIRSHIP_DECK         , LocationType.NPC_REWARD),
    NPCRewardName.HARP_STRING_TILE                 : LocationData(NPCRewardID.HARP_STRING_TILE                , LocationType.NPC_REWARD),
    NPCRewardName.NORTHEASTERN_MERMAID_HERB        : LocationData(NPCRewardID.NORTHEASTERN_MERMAID_HERB       , LocationType.NPC_REWARD),
    NPCRewardName.BUBBLE_ARMOR_MERMAID             : LocationData(NPCRewardID.BUBBLE_ARMOR_MERMAID            , LocationType.NPC_REWARD),
    NPCRewardName.MAGIC_FLARE_MERMAID              : LocationData(NPCRewardID.MAGIC_FLARE_MERMAID             , LocationType.NPC_REWARD),
    NPCRewardName.MERMAID_QUEEN                    : LocationData(NPCRewardID.MERMAID_QUEEN                   , LocationType.NPC_REWARD),
    NPCRewardName.REDHOT_STICK_MERMAID             : LocationData(NPCRewardID.REDHOT_STICK_MERMAID            , LocationType.NPC_REWARD),
    NPCRewardName.LUE                              : LocationData(NPCRewardID.LUE                             , LocationType.NPC_REWARD),
    NPCRewardName.ROCKBIRD_CRYSTAL                 : LocationData(NPCRewardID.ROCKBIRD_CRYSTAL                , LocationType.NPC_REWARD),
    NPCRewardName.SEABED_CRYSTAL_NEAR_BLESTER      : LocationData(NPCRewardID.SEABED_CRYSTAL_NEAR_BLESTER     , LocationType.NPC_REWARD),
    NPCRewardName.SEABED_CRYSTAL_NEAR_DUREAN       : LocationData(NPCRewardID.SEABED_CRYSTAL_NEAR_DUREAN      , LocationType.NPC_REWARD),
    NPCRewardName.MAGICIAN_SOUL                    : LocationData(NPCRewardID.MAGICIAN_SOUL                   , LocationType.NPC_REWARD, RuleFlag.HAS_SWORD),
    NPCRewardName.MOLE_SOUL_OF_LIGHT               : LocationData(NPCRewardID.MOLE_SOUL_OF_LIGHT              , LocationType.NPC_REWARD),
    NPCRewardName.ANGELFISH_SOUL_OF_SHIELD         : LocationData(NPCRewardID.ANGELFISH_SOUL_OF_SHIELD        , LocationType.NPC_REWARD),
    NPCRewardName.GREAT_DOOR_SOUL_OF_DETECTION     : LocationData(NPCRewardID.GREAT_DOOR_SOUL_OF_DETECTION    , LocationType.NPC_REWARD),
    NPCRewardName.SOLDIER_SOUL_OF_REALITY          : LocationData(NPCRewardID.SOLDIER_SOUL_OF_REALITY         , LocationType.NPC_REWARD),
}

lair_table = {
    LairName.OLD_WOMAN                     : LocationData(LairID.OLD_WOMAN                    , LocationType.LAIR),
    LairName.TOOL_SHOP_OWNER               : LocationData(LairID.TOOL_SHOP_OWNER              , LocationType.LAIR),
    LairName.TULIP                         : LocationData(LairID.TULIP                        , LocationType.LAIR),
    LairName.BRIDGE_GUARD                  : LocationData(LairID.BRIDGE_GUARD                 , LocationType.LAIR),
    LairName.VILLAGE_CHIEF                 : LocationData(LairID.VILLAGE_CHIEF                , LocationType.LAIR),
    LairName.IVY_CHEST_ROOM                : LocationData(LairID.IVY_CHEST_ROOM               , LocationType.LAIR),
    LairName.WATER_MILL                    : LocationData(LairID.WATER_MILL                   , LocationType.LAIR),
    LairName.GOAT_HERB                     : LocationData(LairID.GOAT_HERB                    , LocationType.LAIR),
    LairName.LISA                          : LocationData(LairID.LISA                         , LocationType.LAIR),
    LairName.TULIP2                        : LocationData(LairID.TULIP2                       , LocationType.LAIR),
    LairName.ARCHITECT                     : LocationData(LairID.ARCHITECT                    , LocationType.LAIR),
    LairName.IVY                           : LocationData(LairID.IVY                          , LocationType.LAIR),
    LairName.GOAT                          : LocationData(LairID.GOAT                         , LocationType.LAIR),
    LairName.TEDDY                         : LocationData(LairID.TEDDY                        , LocationType.LAIR),
    LairName.TULIP3                        : LocationData(LairID.TULIP3                       , LocationType.LAIR),
    LairName.LEOS_HOUSE                    : LocationData(LairID.LEOS_HOUSE                   , LocationType.LAIR),
    LairName.LONELY_GOAT                   : LocationData(LairID.LONELY_GOAT                  , LocationType.LAIR),
    LairName.TULIP_PASS                    : LocationData(LairID.TULIP_PASS                   , LocationType.LAIR),
    LairName.BOY_CABIN                     : LocationData(LairID.BOY_CABIN                    , LocationType.LAIR),
    LairName.BOY_CAVE                      : LocationData(LairID.BOY_CAVE                     , LocationType.LAIR),
    LairName.OLD_MAN                       : LocationData(LairID.OLD_MAN                      , LocationType.LAIR),
    LairName.OLD_MAN2                      : LocationData(LairID.OLD_MAN2                     , LocationType.LAIR),
    LairName.IVY2                          : LocationData(LairID.IVY2                         , LocationType.LAIR),
    LairName.IVY_EMBLEM_A                  : LocationData(LairID.IVY_EMBLEM_A                 , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.IVY_RECOVERY_SWORD            : LocationData(LairID.IVY_RECOVERY_SWORD           , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.TULIP4                        : LocationData(LairID.TULIP4                       , LocationType.LAIR),
    LairName.GOAT2                         : LocationData(LairID.GOAT2                        , LocationType.LAIR),
    LairName.BIRD_RED_HOT_MIRROR           : LocationData(LairID.BIRD_RED_HOT_MIRROR          , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.BIRD                          : LocationData(LairID.BIRD                         , LocationType.LAIR),
    LairName.DOG                           : LocationData(LairID.DOG                          , LocationType.LAIR),
    LairName.DOG2                          : LocationData(LairID.DOG2                         , LocationType.LAIR),
    LairName.DOG3                          : LocationData(LairID.DOG3                         , LocationType.LAIR),
    LairName.MOLE_SHIELD_BRACELET          : LocationData(LairID.MOLE_SHIELD_BRACELET         , LocationType.LAIR),
    LairName.SQUIRREL_EMBLEM_C             : LocationData(LairID.SQUIRREL_EMBLEM_C            , LocationType.LAIR),
    LairName.SQUIRREL_PSYCHO_SWORD         : LocationData(LairID.SQUIRREL_PSYCHO_SWORD        , LocationType.LAIR),
    LairName.BIRD2                         : LocationData(LairID.BIRD2                        , LocationType.LAIR),
    LairName.MOLE_SOUL_OF_LIGHT            : LocationData(LairID.MOLE_SOUL_OF_LIGHT           , LocationType.LAIR),
    LairName.DEER                          : LocationData(LairID.DEER                         , LocationType.LAIR),
    LairName.CROCODILE                     : LocationData(LairID.CROCODILE                    , LocationType.LAIR),
    LairName.SQUIRREL                      : LocationData(LairID.SQUIRREL                     , LocationType.LAIR),
    LairName.GREENWOODS_GUARDIAN           : LocationData(LairID.GREENWOODS_GUARDIAN          , LocationType.LAIR),
    LairName.MOLE                          : LocationData(LairID.MOLE                         , LocationType.LAIR),
    LairName.DOG4                          : LocationData(LairID.DOG4                         , LocationType.LAIR),
    LairName.SQUIRREL_ICE_ARMOR            : LocationData(LairID.SQUIRREL_ICE_ARMOR           , LocationType.LAIR),
    LairName.SQUIRREL2                     : LocationData(LairID.SQUIRREL2                    , LocationType.LAIR),
    LairName.DOG5                          : LocationData(LairID.DOG5                         , LocationType.LAIR),
    LairName.CROCODILE2                    : LocationData(LairID.CROCODILE2                   , LocationType.LAIR),
    LairName.MOLE2                         : LocationData(LairID.MOLE2                        , LocationType.LAIR),
    LairName.SQUIRREL3                     : LocationData(LairID.SQUIRREL3                    , LocationType.LAIR),
    LairName.BIRD_GREENWOOD_LEAF           : LocationData(LairID.BIRD_GREENWOOD_LEAF          , LocationType.LAIR),
    LairName.MOLE3                         : LocationData(LairID.MOLE3                        , LocationType.LAIR),
    LairName.DEER_MAGIC_BELL               : LocationData(LairID.DEER_MAGIC_BELL              , LocationType.LAIR),
    LairName.BIRD3                         : LocationData(LairID.BIRD3                        , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.CROCODILE3                    : LocationData(LairID.CROCODILE3                   , LocationType.LAIR),
    LairName.MONMO                         : LocationData(LairID.MONMO                        , LocationType.LAIR),
    LairName.DOLPHIN                       : LocationData(LairID.DOLPHIN                      , LocationType.LAIR),
    LairName.ANGELFISH                     : LocationData(LairID.ANGELFISH                    , LocationType.LAIR),
    LairName.MERMAID                       : LocationData(LairID.MERMAID                      , LocationType.LAIR),
    LairName.ANGELFISH2                    : LocationData(LairID.ANGELFISH2                   , LocationType.LAIR),
    LairName.MERMAID_PEARL                 : LocationData(LairID.MERMAID_PEARL                , LocationType.LAIR),
    LairName.MERMAID2                      : LocationData(LairID.MERMAID2                     , LocationType.LAIR),
    LairName.DOLPHIN_SAVES_LUE             : LocationData(LairID.DOLPHIN_SAVES_LUE            , LocationType.LAIR),
    LairName.MERMAID_STATUE_BLESTER        : LocationData(LairID.MERMAID_STATUE_BLESTER       , LocationType.LAIR),
    LairName.MERMAID_RED_HOT_STICK         : LocationData(LairID.MERMAID_RED_HOT_STICK        , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.LUE                           : LocationData(LairID.LUE                          , LocationType.LAIR),
    LairName.MERMAID3                      : LocationData(LairID.MERMAID3                     , LocationType.LAIR),
    LairName.MERMAID_NANA                  : LocationData(LairID.MERMAID_NANA                 , LocationType.LAIR),
    LairName.MERMAID4                      : LocationData(LairID.MERMAID4                     , LocationType.LAIR),
    LairName.DOLPHIN2                      : LocationData(LairID.DOLPHIN2                     , LocationType.LAIR),
    LairName.MERMAID_STATUE_ROCKBIRD       : LocationData(LairID.MERMAID_STATUE_ROCKBIRD      , LocationType.LAIR),
    LairName.MERMAID_BUBBLE_ARMOR          : LocationData(LairID.MERMAID_BUBBLE_ARMOR         , LocationType.LAIR),
    LairName.MERMAID5                      : LocationData(LairID.MERMAID5                     , LocationType.LAIR),
    LairName.MERMAID6                      : LocationData(LairID.MERMAID6                     , LocationType.LAIR),
    LairName.MERMAID_TEARS                 : LocationData(LairID.MERMAID_TEARS                , LocationType.LAIR),
    LairName.MERMAID_STATUE_DUREAN         : LocationData(LairID.MERMAID_STATUE_DUREAN        , LocationType.LAIR),
    LairName.ANGELFISH3                    : LocationData(LairID.ANGELFISH3                   , LocationType.LAIR),
    LairName.ANGELFISH_SOUL_OF_SHIELD      : LocationData(LairID.ANGELFISH_SOUL_OF_SHIELD     , LocationType.LAIR),
    LairName.MERMAID_MAGIC_FLARE           : LocationData(LairID.MERMAID_MAGIC_FLARE          , LocationType.LAIR),
    LairName.MERMAID_QUEEN                 : LocationData(LairID.MERMAID_QUEEN                , LocationType.LAIR),
    LairName.MERMAID_STATUE_GHOST_SHIP     : LocationData(LairID.MERMAID_STATUE_GHOST_SHIP    , LocationType.LAIR, RuleFlag.HAS_THUNDER),
    LairName.DOLPHIN_SECRET_CAVE           : LocationData(LairID.DOLPHIN_SECRET_CAVE          , LocationType.LAIR),
    LairName.MERMAID7                      : LocationData(LairID.MERMAID7                     , LocationType.LAIR),
    LairName.ANGELFISH4                    : LocationData(LairID.ANGELFISH4                   , LocationType.LAIR),
    LairName.MERMAID8                      : LocationData(LairID.MERMAID8                     , LocationType.LAIR),
    LairName.DOLPHIN_PEARL                 : LocationData(LairID.DOLPHIN_PEARL                , LocationType.LAIR),
    LairName.MERMAID9                      : LocationData(LairID.MERMAID9                     , LocationType.LAIR),
    LairName.GRANDPA                       : LocationData(LairID.GRANDPA                      , LocationType.LAIR),
    LairName.GIRL                          : LocationData(LairID.GIRL                         , LocationType.LAIR),
    LairName.MUSHROOM                      : LocationData(LairID.MUSHROOM                     , LocationType.LAIR),
    LairName.BOY                           : LocationData(LairID.BOY                          , LocationType.LAIR),
    LairName.GRANDPA2                      : LocationData(LairID.GRANDPA2                     , LocationType.LAIR),
    LairName.SNAIL_JOCKEY                  : LocationData(LairID.SNAIL_JOCKEY                 , LocationType.LAIR),
    LairName.NOME                          : LocationData(LairID.NOME                         , LocationType.LAIR),
    LairName.BOY2                          : LocationData(LairID.BOY2                         , LocationType.LAIR),
    LairName.MUSHROOM_EMBLEM_F             : LocationData(LairID.MUSHROOM_EMBLEM_F            , LocationType.LAIR),
    LairName.DANCING_GRANDMA               : LocationData(LairID.DANCING_GRANDMA              , LocationType.LAIR),
    LairName.DANCING_GRANDMA2              : LocationData(LairID.DANCING_GRANDMA2             , LocationType.LAIR),
    LairName.SNAIL_EMBLEM_E                : LocationData(LairID.SNAIL_EMBLEM_E               , LocationType.LAIR),
    LairName.BOY_MUSHROOM_SHOES            : LocationData(LairID.BOY_MUSHROOM_SHOES           , LocationType.LAIR),
    LairName.GRANDMA                       : LocationData(LairID.GRANDMA                      , LocationType.LAIR),
    LairName.GIRL2                         : LocationData(LairID.GIRL2                        , LocationType.LAIR),
    LairName.MUSHROOM2                     : LocationData(LairID.MUSHROOM2                    , LocationType.LAIR),
    LairName.SNAIL_RACER                   : LocationData(LairID.SNAIL_RACER                  , LocationType.LAIR),
    LairName.SNAIL_RACER2                  : LocationData(LairID.SNAIL_RACER2                 , LocationType.LAIR),
    LairName.GIRL3                         : LocationData(LairID.GIRL3                        , LocationType.LAIR),
    LairName.MUSHROOM3                     : LocationData(LairID.MUSHROOM3                    , LocationType.LAIR),
    LairName.SNAIL                         : LocationData(LairID.SNAIL                        , LocationType.LAIR),
    LairName.GRANDPA3                      : LocationData(LairID.GRANDPA3                     , LocationType.LAIR),
    LairName.SNAIL2                        : LocationData(LairID.SNAIL2                       , LocationType.LAIR),
    LairName.GRANDPA4                      : LocationData(LairID.GRANDPA4                     , LocationType.LAIR),
    LairName.GRANDPA_LUNE                  : LocationData(LairID.GRANDPA_LUNE                 , LocationType.LAIR),
    LairName.GRANDPA5                      : LocationData(LairID.GRANDPA5                     , LocationType.LAIR),
    LairName.MOUNTAIN_KING                 : LocationData(LairID.MOUNTAIN_KING                , LocationType.LAIR),
    LairName.PLANT_HERB                    : LocationData(LairID.PLANT_HERB                   , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.PLANT                         : LocationData(LairID.PLANT                        , LocationType.LAIR),
    LairName.CHEST_OF_DRAWERS_MYSTIC_ARMOR : LocationData(LairID.CHEST_OF_DRAWERS_MYSTIC_ARMOR, LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.CAT                           : LocationData(LairID.CAT                          , LocationType.LAIR),
    LairName.GREAT_DOOR_ZANTETSU_SWORD     : LocationData(LairID.GREAT_DOOR_ZANTETSU_SWORD    , LocationType.LAIR),
    LairName.CAT2                          : LocationData(LairID.CAT2                         , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.GREAT_DOOR                    : LocationData(LairID.GREAT_DOOR                   , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.CAT3                          : LocationData(LairID.CAT3                         , LocationType.LAIR),
    LairName.MODEL_TOWN1                   : LocationData(LairID.MODEL_TOWN1                  , LocationType.LAIR),
    LairName.GREAT_DOOR_MODEL_TOWNS        : LocationData(LairID.GREAT_DOOR_MODEL_TOWNS       , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.STEPS_UPSTAIRS                : LocationData(LairID.STEPS_UPSTAIRS               , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.CAT_DOOR_KEY                  : LocationData(LairID.CAT_DOOR_KEY                 , LocationType.LAIR),
    LairName.MOUSE                         : LocationData(LairID.MOUSE                        , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.MARIE                         : LocationData(LairID.MARIE                        , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.DOLL                          : LocationData(LairID.DOLL                         , LocationType.LAIR, RuleFlag.CAN_CUT_METAL),
    LairName.CHEST_OF_DRAWERS              : LocationData(LairID.CHEST_OF_DRAWERS             , LocationType.LAIR),
    LairName.PLANT2                        : LocationData(LairID.PLANT2                       , LocationType.LAIR),
    LairName.MOUSE2                        : LocationData(LairID.MOUSE2                       , LocationType.LAIR),
    LairName.MOUSE_SPARK_BOMB              : LocationData(LairID.MOUSE_SPARK_BOMB             , LocationType.LAIR, RuleFlag.HAS_MAGIC),
    LairName.MOUSE3                        : LocationData(LairID.MOUSE3                       , LocationType.LAIR, RuleFlag.HAS_MAGIC),
    LairName.GREAT_DOOR_SOUL_OF_DETECTION  : LocationData(LairID.GREAT_DOOR_SOUL_OF_DETECTION , LocationType.LAIR),
    LairName.MODEL_TOWN2                   : LocationData(LairID.MODEL_TOWN2                  , LocationType.LAIR, RuleFlag.HAS_MAGIC),
    LairName.MOUSE4                        : LocationData(LairID.MOUSE4                       , LocationType.LAIR, RuleFlag.HAS_MAGIC),
    LairName.STEPS_MARIE                   : LocationData(LairID.STEPS_MARIE                  , LocationType.LAIR, RuleFlag.HAS_MAGIC),
    LairName.CHEST_OF_DRAWERS2             : LocationData(LairID.CHEST_OF_DRAWERS2            , LocationType.LAIR),
    LairName.PLANT_ACTINIDIA_LEAVES        : LocationData(LairID.PLANT_ACTINIDIA_LEAVES       , LocationType.LAIR),
    LairName.MOUSE5                        : LocationData(LairID.MOUSE5                       , LocationType.LAIR),
    LairName.CAT4                          : LocationData(LairID.CAT4                         , LocationType.LAIR),
    LairName.STAIRS_POWER_PLANT            : LocationData(LairID.STAIRS_POWER_PLANT           , LocationType.LAIR),
    LairName.SOLDIER                       : LocationData(LairID.SOLDIER                      , LocationType.LAIR),
    LairName.SOLDIER2                      : LocationData(LairID.SOLDIER2                     , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER3                      : LocationData(LairID.SOLDIER3                     , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER_ELEMENTAL_MAIL        : LocationData(LairID.SOLDIER_ELEMENTAL_MAIL       , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER4                      : LocationData(LairID.SOLDIER4                     , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER5                      : LocationData(LairID.SOLDIER5                     , LocationType.LAIR),
    LairName.SINGER_CONCERT_HALL           : LocationData(LairID.SINGER_CONCERT_HALL          , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER6                      : LocationData(LairID.SOLDIER6                     , LocationType.LAIR),
    LairName.MAID                          : LocationData(LairID.MAID                         , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER_LEFT_TOWER            : LocationData(LairID.SOLDIER_LEFT_TOWER           , LocationType.LAIR),
    LairName.SOLDIER_DOK                   : LocationData(LairID.SOLDIER_DOK                  , LocationType.LAIR),
    LairName.SOLDIER_PLATINUM_CARD         : LocationData(LairID.SOLDIER_PLATINUM_CARD        , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SINGER                        : LocationData(LairID.SINGER                       , LocationType.LAIR, RuleFlag.CAN_CUT_SPIRIT),
    LairName.SOLDIER_SOUL_OF_REALITY       : LocationData(LairID.SOLDIER_SOUL_OF_REALITY      , LocationType.LAIR),
    LairName.MAID2                         : LocationData(LairID.MAID2                        , LocationType.LAIR),
    LairName.QUEEN_MAGRIDD                 : LocationData(LairID.QUEEN_MAGRIDD                , LocationType.LAIR),
    LairName.SOLDIER_WITH_LEO              : LocationData(LairID.SOLDIER_WITH_LEO             , LocationType.LAIR),
    LairName.SOLDIER_RIGHT_TOWER           : LocationData(LairID.SOLDIER_RIGHT_TOWER          , LocationType.LAIR),
    LairName.DR_LEO                        : LocationData(LairID.DR_LEO                       , LocationType.LAIR),
    LairName.SOLDIER7                      : LocationData(LairID.SOLDIER7                     , LocationType.LAIR),
    LairName.SOLDIER8                      : LocationData(LairID.SOLDIER8                     , LocationType.LAIR),
    LairName.MAID_HERB                     : LocationData(LairID.MAID_HERB                    , LocationType.LAIR),
    LairName.SOLDIER_CASTLE                : LocationData(LairID.SOLDIER_CASTLE               , LocationType.LAIR),
    LairName.SOLDIER9                      : LocationData(LairID.SOLDIER9                     , LocationType.LAIR),
    LairName.SOLDIER10                     : LocationData(LairID.SOLDIER10                    , LocationType.LAIR),
    LairName.SOLDIER11                     : LocationData(LairID.SOLDIER11                    , LocationType.LAIR),
    LairName.KING_MAGRIDD                  : LocationData(LairID.KING_MAGRIDD                 , LocationType.LAIR),
}

all_locations_table = {
    **chest_table,
    **npc_reward_table,
    **lair_table,
}

boss_lair_names_table = {
    LairName.VILLAGE_CHIEF,
    LairName.GREENWOODS_GUARDIAN,
    LairName.MERMAID_QUEEN,
    LairName.MOUNTAIN_KING,
    LairName.MARIE,
    LairName.KING_MAGRIDD,
}

village_leader_names_table = {
    NPCRewardName.VILLAGE_CHIEF,
    NPCRewardName.GREENWOODS_GUARDIAN,
    NPCRewardName.MERMAID_QUEEN,
    NPCRewardName.NOME,
    NPCRewardName.MARIE,
    NPCRewardName.KING_MAGRIDD,
}

